### ISSUE TITLE
ValueChangeSoundPlayer performance and crashing with NumberControl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#164]
I’m writing a scenery-phet demo for a UI component.  The demo involves a NumberControl, which has option `delta`.   ValueChangeSoundPlayer seems to have problems (performance and crashing) when `delta` has a small value.

With `delta: 0.0001` the demo starts up fine. 

With `delta: 0.00001`, the demo takes ~14 seconds to start.  

With `delta: 0.000001 , it hangs for ~14 seconds, then crashes in ValueChangeSoundPlayer with this stack trace:

```
Uncaught RangeError: Invalid array length
    at baseTimes (lodash-4.17.4.js:997:21)
    at Function.times (lodash-4.17.4.js:16095:20)
    at new ValueChangeSoundPlayer (ValueChangeSoundPlayer.ts:204:9)
    at new Slider (Slider.ts:237:32)
    at new HSlider (HSlider.ts:28:5)
    at new NumberControl (NumberControl.ts:384:19)
```

**Comment by pixelzoom** [comment]
To reproduce in scenery-phet demo:

* In ComponentsScreenView `demoScientificNotationNode`, change this `delta` value:

```
  const valueControl = new NumberControl( '', valueProperty, valueProperty.range, {
    delta: 0.001,
```

* Run the demo with `?brand=phet&ea&debugger&component=ScientificNotationNode&initialScreen=2`

**Comment by pixelzoom** [comment]
I can't do what I need to do in scenery-phet demo because of this problem.  So I'm going to replace NumberControl with Keypad -- which is probably a UI imporvement in any case.

If you want to reproduce in scenery-phet demo, you'll need to check out 3ea43d80 of ComponentsScreenView.js.

**Comment by jbphet** [comment]
This is a very interesting test case.  Looking at the code for `ValueChangeSoundPlayer`, I can see that I made an implicit assumption that there would never be a need to generate sounds for a very large number of values, so I pre-computed the thresholds during construction.  In @pixelzoom's test, he created a situation where there were something like 20 million threshold values.  Didn't go well.  I've rewritten the code that detects threshold crossings to do so algorithmically instead of from pre-computed values.  I regression tested using tambo, fourier, geometric optics, and the particular version of the scenery-phet demo that @pixelzoom mentions above.  It seems to work fine.

@pixelzoom - You're welcome to have a look and to re-try your original UI idea if you like.  Otherwise feel free to close.
