### ISSUE TITLE
CT: Uncaught Error: Assertion failed: Tried to insert a disposed Node

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#169]
I'm seeing a couple of the errors listed in the title in CT, and I just ran the fuzz test and was able to duplicate it.  I should investigate.

Here's the info from CT:

<details>

```
tambo : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663073934405/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663073934405%22%2C%22timestamp%22%3A1663088221960%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663073934405/assert/js/assert.js:28:13)
at assert (Node.ts:853:14)
at insertChild (Node.ts:1081:15)
at setChildren (Node.ts:1108:9)
at (Node.ts:6306:10)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663073934405/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663073934405/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6289:6)
at mutate (Node.ts:825:11)
at (AquaRadioButtonGroup.ts:108:22)
id: Bayes Puppeteer
Snapshot from 9/13/2022, 6:58:54 AM
```

</details>

Here is the stack trace from when I duplicated it locally:

<details>

```
window.assertions.assertFunction (assert.js:28)
insertChild (Node.ts:853)
setChildren (Node.ts:1081)
set children (Node.ts:1108)
(anonymous) (Node.ts:6306)
arrayEach (lodash-4.17.4.js:537)
forEach (lodash-4.17.4.js:9359)
mutate (Node.ts:6289)
Node (Node.ts:825)
AquaRadioButtonGroup (AquaRadioButtonGroup.ts:108)
createNode (UIComponentsScreenView.ts:138)
(anonymous) (DemosScreenView.ts:158)
emit (TinyEmitter.ts:95)
_notifyListeners (ReadOnlyProperty.ts:304)
unguardedSet (ReadOnlyProperty.ts:255)
set (ReadOnlyProperty.ts:239)
set value (Property.ts:54)
press (CarouselComboBox.ts:277)
onPress (PressListener.ts:727)
execute (PhetioAction.ts:124)
press (PressListener.ts:485)
down (PressListener.ts:770)
dispatchToListeners (Input.ts:1804)
dispatchToTargets (Input.ts:1841)
dispatchEvent (Input.ts:1759)
downEvent (Input.ts:1594)
Input.touchStartAction.PhetioAction.phetioPlayback (Input.ts:493)
execute (PhetioAction.ts:124)
touchStart (Input.ts:1274)
touchStart (InputFuzzer.js? [sm]:205)
InputFuzzer.touchStartAction (InputFuzzer.js? [sm]:47)
fuzzEvents (InputFuzzer.js? [sm]:105)
fuzzInputEvents (SimDisplay.ts:200)
runAnimationLoop (Sim.ts:973)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
requestAnimationFrame (async)
runAnimationLoop (Sim.ts:965)
```

</details>

**Comment by jbphet** [comment]
Apparently we can no longer reuse combo box items, so I changed the code to recreate them instead.  Closing.
