### ISSUE TITLE
CT a sound player that supports playback rate changes is required when a playback rate mapper is used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#174]
Probably related to https://github.com/phetsims/my-solar-system/issues/70
```
tambo : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670597313079%22%2C%22timestamp%22%3A1670600532404%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/assert/js/assert.js:28:13)
at assert (ValueChangeSoundPlayer.ts:175:14)
at (SliderPitchChangeSoundGenerator.ts:36:4)
at (SliderSoundTestNode.ts:86:26)
at (UIComponentsScreenView.ts:198:49)
at createNode (DemosScreenView.ts:161:25)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
id: Bayes Puppeteer
Snapshot from 12/9/2022, 7:48:33 AM

----------------------------------

tambo : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670597313079%22%2C%22timestamp%22%3A1670599803217%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/assert/js/assert.js:28:13)
at assert (ValueChangeSoundPlayer.ts:175:14)
at (SliderPitchChangeSoundGenerator.ts:36:4)
at (SliderSoundTestNode.ts:86:26)
at (UIComponentsScreenView.ts:198:49)
at createNode (DemosScreenView.ts:161:25)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
id: Bayes Puppeteer
Snapshot from 12/9/2022, 7:48:33 AM

----------------------------------

tambo : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1670597313079%22%2C%22timestamp%22%3A1670601313701%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/assert/js/assert.js:28:13)
at assert (ValueChangeSoundPlayer.ts:175:14)
at (SliderPitchChangeSoundGenerator.ts:36:4)
at (SliderSoundTestNode.ts:86:26)
at (UIComponentsScreenView.ts:198:49)
at createNode (DemosScreenView.ts:161:25)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
id: Bayes Puppeteer
Snapshot from 12/9/2022, 7:48:33 AM

----------------------------------

tambo : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1670597313079%22%2C%22timestamp%22%3A1670600902355%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
Error: Assertion failed: a sound player that supports playback rate changes is required when a playback rate mapper is used
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1670597313079/assert/js/assert.js:28:13)
at assert (ValueChangeSoundPlayer.ts:175:14)
at (SliderPitchChangeSoundGenerator.ts:36:4)
at (SliderSoundTestNode.ts:86:26)
at (UIComponentsScreenView.ts:198:49)
at createNode (DemosScreenView.ts:161:25)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
id: Bayes Puppeteer
Snapshot from 12/9/2022, 7:48:33 AM
```

**Comment by jbphet** [comment]
@pixelzoom - the commit https://github.com/phetsims/tambo/commit/9bb449fd54f6cc592af26e0f4d4e3875d94ed1f2 is breaking CT because the `hasOwnProperty` call in `ValueChangeSoundPlayer` doesn't appear to be working.  Is there a better, more type safe way to do this?

**Comment by pixelzoom** [comment]
I reverted the change to ValueChangeSoundPlayer, and restored the 2 ts-expect-error comment.  I tried, but you'll have to figure out how to address them.

The assertion tests that need the 2 ts-expect-error comments would not be necessary if you had correct types for the related options. Both of these are incorrect; they both should be of a type that has `setPlaybackRate`.

```
   // The sound player for movement in the middle of the range in the up direction.
  middleMovingUpSoundPlayer?: TSoundPlayer | SoundClip;

  // The sound player for movement in the middle of the range in the down direction.
  middleMovingDownSoundPlayer?: TSoundPlayer | SoundClip;
```

**Comment by jbphet** [comment]
This has now been addressed in https://github.com/phetsims/tambo/commit/a8e3eb8142f3314a7155cd1236877d0d2f376486, closing.
